[functions.gemini-chat]
enabled = true
# TODO: REVERT FOR PRODUCTION! Temporarily disabled JWT verification for testing.
verify_jwt = false
import_map = "./functions/gemini-chat/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gemini-chat/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gemini-chat/*.html" ]
