[functions.process-session-end]
enabled = true
verify_jwt = true
entrypoint = "./functions/process-session-end/index.ts"

[functions.truncate-history]
enabled = true
verify_jwt = true
entrypoint = "./functions/truncate-history/index.ts"

[functions.rag-dynamic-context]
enabled = true
verify_jwt = true
entrypoint = "./functions/rag-dynamic-context/index.ts"

[functions.openai-chat]
enabled = true
verify_jwt = true
entrypoint = "./functions/openai-chat/index.ts"

[functions.create-session]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-session/index.ts"

[functions.generate-embeddings]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-embeddings/index.ts"